import {
  Cpu, FlaskConical, Briefcase, Scale, HeartPulse,
  Code2, Zap, Building2, TrendingUp, Dna, Calculator, Leaf, BookOpen,
  Atom, Computer, BriefcaseBusiness, Settings,
  Lightbulb, ShieldCheck, Users, Target, Heart, Eye,
  GraduationCap, Landmark,
  Info, History, Award, ClipboardList, Send,
  LayoutGrid, UserCog, Wallet, ClipboardCheck, Presentation,
  Trees, Handshake, Newspaper, Bell, CalendarDays, ScrollText,
  Phone, Library, IdCard, Search, Bus,
  type LucideIcon,
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  Cpu,
  FlaskConical,
  Briefcase,
  Scale,
  HeartPulse,
  Code2,
  Zap,
  Building2,
  TrendingUp,
  Dna,
  Calculator,
  Leaf,
  BookOpen,
  Atom,
  Computer,
  BriefcaseBusiness,
  Settings,
  Lightbulb,
  ShieldCheck,
  Users,
  Target,
  Heart,
  Eye,
  GraduationCap,
  Landmark,
  Info,
  History,
  Award,
  ClipboardList,
  Send,
  LayoutGrid,
  UserCog,
  Wallet,
  ClipboardCheck,
  Presentation,
  Trees,
  Handshake,
  Newspaper,
  Bell,
  CalendarDays,
  ScrollText,
  Phone,
  Library,
  IdCard,
  Search,
  Bus,
}
