import {
  Cpu, FlaskConical, Briefcase, Scale, HeartPulse,
  Code2, Zap, Building2, TrendingUp, Dna, Calculator, Leaf, BookOpen,
  Atom, Computer, BriefcaseBusiness, Settings,
  Lightbulb, ShieldCheck, Users, Target, Heart, Eye,
  GraduationCap, Landmark,
  Info, History, Award, ClipboardList, Send,
  LayoutGrid, UserCog, Wallet, ClipboardCheck, Presentation,
  Trees, Handshake, Newspaper, Bell, CalendarDays, ScrollText,
  Phone, Library, IdCard, Search, Bus,
  Accessibility, BarChart3, Beaker, BrainCircuit, Camera, ChartNoAxesCombined, CircuitBoard, Clock3, Coffee, Compass, Download, Dumbbell, FileCheck2, FileText, Globe, Globe2, HandHeart, HeartHandshake, Laptop2, LayoutDashboard, Mail, MapPin, MessageSquare, Microscope, Monitor, Music, Music2, Network, Palette, Plane, Rocket, Sparkles, Star, Trophy, UserCheck, UserRound, UsersRound, Utensils, Volleyball, Waypoints, Wrench,
  type LucideIcon,
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  Cpu,
  FlaskConical,
  Briefcase,
  Scale,
  HeartPulse,
  Code2,
  Zap,
  Building2,
  TrendingUp,
  Dna,
  Calculator,
  Leaf,
  BookOpen,
  Atom,
  Computer,
  BriefcaseBusiness,
  Settings,
  Lightbulb,
  ShieldCheck,
  Users,
  Target,
  Heart,
  Eye,
  GraduationCap,
  Landmark,
  Info,
  History,
  Award,
  ClipboardList,
  Send,
  LayoutGrid,
  UserCog,
  Wallet,
  ClipboardCheck,
  Presentation,
  Trees,
  Handshake,
  Newspaper,
  Bell,
  CalendarDays,
  ScrollText,
  Phone,
  Library,
  IdCard,
  Search,
  Bus,
  Accessibility,
  BarChart3,
  Beaker,
  BrainCircuit,
  Camera,
  ChartNoAxesCombined,
  CircuitBoard,
  Clock3,
  Coffee,
  Compass,
  Download,
  Dumbbell,
  FileCheck2,
  FileText,
  Globe,
  Globe2,
  HandHeart,
  HeartHandshake,
  Laptop2,
  LayoutDashboard,
  Mail,
  MapPin,
  MessageSquare,
  Microscope,
  Monitor,
  Music,
  Music2,
  Network,
  Palette,
  Plane,
  Rocket,
  Sparkles,
  Star,
  Trophy,
  UserCheck,
  UserRound,
  UsersRound,
  Utensils,
  Volleyball,
  Waypoints,
  Wrench,
}
