import Link from "next/link"
import { PageShell } from "@/components/page-shell"
import { PageHero } from "@/components/page-hero"
import { Section } from "@/components/blocks"
import { SectionHeading } from "@/components/section-heading"
import { CTASection } from "@/components/cta-section"
import { FACULTIES, PROGRAMS, NEWS, EVENTS, NOTICES, FACULTY_MEMBERS, RESEARCH_AREAS } from "@/lib/data"
import { imageUrl } from "@/lib/site-assets"
import { ICON_MAP } from "@/lib/icon-map"
import {
  GENERIC_PAGE_MAP, SUB_PAGE_MAP, type PageConfig,
  ADMIN_QUICK_LINKS, ACADEMICS_CARDS, MISSION_VALUES, LEADERSHIP_ROLES,
  ADMISSIONS_STEPS, ADMISSIONS_CHECKLIST, ADMISSIONS_DATES,
  RESEARCH_AREA_ICONS, RESEARCH_PATHWAYS, CAREER_CARDS, LIBRARY_FEATURES,
  SITEMAP_GROUPS, CAMPUS_LIFE_CARDS,
} from "@/lib/data/slug-pages"
import {
  ArrowRight, CalendarDays, CheckCircle2, Clock3, Download,
  Mail, Search, Users,
  Library, Briefcase, FileText, ExternalLink,
  Target, Eye
} from "lucide-react"

function Shell({cfg,children}:{cfg:PageConfig,children:React.ReactNode}) {
  return <PageShell><PageHero {...cfg}/>{children}</PageShell>
}

function Cards({items}:{items:{title:string;description:string;icon?:React.ElementType}[]}) {
  return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(({title,description,icon:Icon=CheckCircle2})=><article key={title} className="group rounded-2xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:shadow-lg"><span className="mb-5 flex h-12 w-12 items-center justify-center rounded-xl bg-brand/10 text-brand"><Icon className="h-6 w-6"/></span><h3 className="mb-2 font-serif text-xl font-bold">{title}</h3><p className="text-sm leading-7 text-muted-foreground">{description}</p></article>)}</div>
}

function Programs() {
  return <Section><SectionHeading eyebrow="Study Options" title="Programs designed for the future" description="Browse editable program information across undergraduate and postgraduate levels."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{PROGRAMS.map(p=><article key={p.title} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="mb-5 flex items-center justify-between gap-3"><span className="rounded-full bg-brand/10 px-3 py-1 text-xs font-semibold text-brand">{p.level}</span><span className="text-xs text-muted-foreground">{p.duration}</span></div><h3 className="font-serif text-xl font-bold">{p.title}</h3><p className="mt-2 text-sm text-muted-foreground">{p.faculty}</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-brand">Program information <ArrowRight className="h-4 w-4"/></Link></article>)}</div></Section>
}

function Faculties() {
  return <Section muted><SectionHeading eyebrow="Academic Community" title="Faculties and departments" description="Explore the academic units that support teaching, research and innovation."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{FACULTIES.map(f=><article key={f.slug} className="rounded-2xl border border-border bg-card p-6"><h3 className="font-serif text-xl font-bold">{f.name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{f.description}</p><div className="mt-5 flex flex-wrap gap-2">{f.departments.map(d=><span key={d} className="rounded-full bg-secondary px-3 py-1.5 text-xs font-medium">{d}</span>)}</div></article>)}</div></Section>
}

function ListPage({title,items}:{title:string,items:{title:string;date:string;category:string}[]}) {
  return <Section><SectionHeading eyebrow={title} title={`Latest ${title.toLowerCase()}`} description="This section uses editable sample content. Replace dates, documents and announcements with official university information."/><div className="divide-y divide-border rounded-2xl border border-border bg-card">{items.map((item,i)=><div key={item.title} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><span className="text-xs font-semibold uppercase tracking-wider text-brand">{item.category}</span><h3 className="mt-1 font-semibold">{item.title}</h3><p className="mt-1 text-xs text-muted-foreground">{item.date}</p></div><button className="inline-flex w-fit items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-semibold hover:bg-secondary"><Download className="h-4 w-4"/> View / Download</button></div>)}</div></Section>
}

export default async function GenericPage({params}:{params:Promise<{slug:string[]}>}) {
  const {slug}=await params
  const key=slug.join("/")
  const cfg=GENERIC_PAGE_MAP[key] || SUB_PAGE_MAP[key]
  if (!cfg) return <PageShell><PageHero title="KACST" eyebrow="Page" subtitle="The requested page is being prepared." crumbs={[{label:"Home",href:"/"},{label:"Page"}]}/><Section><div className="py-12 text-center"><h2 className="font-serif text-3xl font-bold">Page not found</h2><Link className="mt-5 inline-flex items-center gap-2 text-brand font-semibold" href="/">Return Home <ArrowRight className="h-4 w-4"/></Link></div></Section></PageShell>

  let body:React.ReactNode

  if (key.startsWith("administration/")) body=<Section><SectionHeading eyebrow="University Administration" title={cfg.title} description={cfg.subtitle} center/><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-border bg-card p-7"><div className="flex h-14 w-14 items-center justify-center rounded-xl bg-brand/10 text-brand"><Users className="h-7 w-7"/></div><h2 className="mt-5 font-serif text-2xl font-bold">Office overview</h2><p className="mt-3 leading-7 text-muted-foreground">This page is ready for the official office-holder name, biography, responsibilities, contact details, circulars and service links. Replace the editable placeholder content with verified university information.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-secondary p-4"><p className="text-xs text-muted-foreground">Office</p><p className="mt-1 font-semibold">KACST Administration</p></div><div className="rounded-xl bg-secondary p-4"><p className="text-xs text-muted-foreground">Contact</p><p className="mt-1 font-semibold">Add official contact</p></div></div></div><div className="rounded-2xl bg-brand-dark p-7 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand-accent">Quick Links</p><div className="mt-5 space-y-2">{ADMIN_QUICK_LINKS.map(([label,href])=><Link key={href} href={href} className="flex items-center justify-between rounded-xl bg-white/10 px-4 py-3 text-sm hover:bg-white/15">{label}<ArrowRight className="h-4 w-4"/></Link>)}</div></div></div></Section>
  else if (key==="academics/programs") body=<Programs/>
  else if (key==="academics/faculties" || key==="academics") body=<><Section><SectionHeading eyebrow="Learning at KACST" title="Education that connects knowledge with opportunity" description="Our academic environment is designed around rigorous learning, practical skills, research and responsible leadership."/><Cards items={ACADEMICS_CARDS.map(c=>({...c,icon:c.icon?ICON_MAP[c.icon]:undefined}))}/></Section><Faculties/></>
  else if (key==="about/history") body=<><Section><SectionHeading eyebrow="Our Story" title="Building a university with a forward-looking vision"/><div className="grid gap-8 lg:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-7"><h3 className="font-serif text-2xl font-bold">A developing academic institution</h3><p className="mt-4 leading-7 text-muted-foreground">KACST is presented here as a modern university concept focused on science, technology, innovation and community impact. Official history, establishment dates and milestones should be inserted from verified university sources.</p></div><div className="space-y-4"><div className="rounded-2xl bg-secondary p-6"><b>Academic vision</b><p className="mt-2 text-sm leading-6 text-muted-foreground">Create an environment where curiosity becomes capability and research becomes impact.</p></div><div className="rounded-2xl bg-secondary p-6"><b>Community vision</b><p className="mt-2 text-sm leading-6 text-muted-foreground">Serve Khulna and beyond through education, innovation and responsible citizenship.</p></div></div></div></Section></>
  else if (key==="about/mission-vision") body=<><Section><div className="grid gap-6 md:grid-cols-2"><div className="rounded-3xl bg-brand-dark p-8 text-white"><Target className="h-9 w-9"/><h2 className="mt-6 font-serif text-3xl font-bold">Our Mission</h2><p className="mt-4 leading-7 text-white/75">To provide quality, accessible education and research opportunities that develop capable professionals, ethical leaders and innovative thinkers.</p></div><div className="rounded-3xl border border-border p-8"><Eye className="h-9 w-9 text-brand"/><h2 className="mt-6 font-serif text-3xl font-bold">Our Vision</h2><p className="mt-4 leading-7 text-muted-foreground">To become a respected center of knowledge, innovation and societal progress in Bangladesh and beyond.</p></div></div></Section><Section muted><SectionHeading eyebrow="Values" title="What guides our work" center/><Cards items={MISSION_VALUES.map(v=>({...v,icon:v.icon?ICON_MAP[v.icon]:undefined}))}/></Section></>
  else if (key==="about/leadership") body=<><Section><SectionHeading eyebrow="Leadership" title="Guided by academic purpose and responsible governance" center/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{LEADERSHIP_ROLES.map((role)=><article key={role} className="rounded-2xl border border-border bg-card p-6"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-brand/10 text-brand"><Users className="h-7 w-7"/></div><h3 className="mt-5 font-serif text-xl font-bold">{role}</h3><p className="mt-2 text-sm text-muted-foreground">Official name and biography — editable placeholder.</p></article>)}</div></Section></>
  else if (key==="admissions" || key.startsWith("admissions/")) body=<><Section><SectionHeading eyebrow="Admissions" title="A clear path from application to enrolment" description="Use these sections as the admissions information architecture. Replace sample requirements and dates with official circulars."/><div className="grid gap-4 md:grid-cols-4">{ADMISSIONS_STEPS.map((x,i)=><div key={x} className="rounded-2xl border border-border p-5"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-brand text-sm font-bold text-white">{i+1}</span><h3 className="mt-4 font-semibold">{x}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">Follow the official instructions for this step.</p></div>)}</div></Section><Section muted><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl bg-card p-7 border border-border"><h3 className="font-serif text-2xl font-bold">General checklist</h3><ul className="mt-5 space-y-3 text-sm text-muted-foreground">{ADMISSIONS_CHECKLIST.map(x=><li key={x} className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-brand"/>{x}</li>)}</ul></div><div className="rounded-2xl bg-card p-7 border border-border"><h3 className="font-serif text-2xl font-bold">Important dates</h3><div className="mt-5 space-y-4">{ADMISSIONS_DATES.map(x=><div key={x} className="flex gap-3 text-sm"><CalendarDays className="h-5 w-5 text-brand"/><span>{x}</span></div>)}</div></div></div></Section><CTASection secondary={{label:"View Academic Programs",href:"/academics/programs"}}/></>
  else if (key==="research" || key.startsWith("research/")) body=<><Section><SectionHeading eyebrow="Research" title="Research that addresses real-world challenges" description="Build an active research culture around interdisciplinary collaboration, innovation and measurable impact."/><Cards items={RESEARCH_AREAS.map((r,i)=>({title:r.title,description:r.description,icon:ICON_MAP[RESEARCH_AREA_ICONS[i%4]]}))}/></Section><Section muted><SectionHeading eyebrow="Research Pathways" title="From idea to impact"/><div className="grid gap-5 md:grid-cols-3">{RESEARCH_PATHWAYS.map((x,i)=><div key={x} className="rounded-2xl bg-card border border-border p-6"><span className="text-sm font-bold text-brand">0{i+1}</span><h3 className="mt-3 font-serif text-xl font-bold">{x}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Create clear pathways for students and faculty to develop, document and share research outcomes.</p></div>)}</div></Section></>
  else if (key==="news") body=<Section><SectionHeading eyebrow="Stories" title="Latest university news"/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{NEWS.map(n=><article key={n.slug} className="overflow-hidden rounded-2xl border border-border bg-card"><img src={imageUrl(n.image)} alt="" className="h-48 w-full object-cover"/><div className="p-5"><span className="text-xs font-semibold text-brand">{n.category} · {n.date}</span><h3 className="mt-2 font-serif text-xl font-bold">{n.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{n.excerpt}</p><Link href="/news" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-brand">Read more <ArrowRight className="h-4 w-4"/></Link></div></article>)}</div></Section>
  else if (key==="events") body=<ListPage title="Events" items={EVENTS}/>
  else if (key==="notice-board") body=<ListPage title="Notices" items={NOTICES}/>
  else if (key==="career") body=<><Section><SectionHeading eyebrow="Careers" title="Build your career with KACST" description="Use this area for verified job circulars, application instructions and recruitment policies."/><div className="grid gap-5 md:grid-cols-2">{CAREER_CARDS.map(x=><article key={x} className="rounded-2xl border border-border p-6"><Briefcase className="h-7 w-7 text-brand"/><h3 className="mt-5 font-serif text-xl font-bold">{x}</h3><p className="mt-2 text-sm text-muted-foreground">Current vacancies and official eligibility details will appear here.</p><Link href="/contact" className="mt-5 inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-semibold hover:bg-secondary">View opportunities <ArrowRight className="h-4 w-4"/></Link></article>)}</div></Section></>
  else if (key==="library") body=<><Section><div className="grid gap-10 lg:grid-cols-2"><div><SectionHeading eyebrow="Library Services" title="A gateway to knowledge"/><p className="leading-7 text-muted-foreground">Provide students and researchers with access to print collections, digital resources, journals, study spaces and research support.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{LIBRARY_FEATURES.map(x=><div key={x} className="rounded-xl bg-secondary p-4 font-semibold">{x}</div>)}</div></div><div className="rounded-3xl bg-brand-dark p-8 text-white"><Library className="h-10 w-10"/><h3 className="mt-5 font-serif text-2xl font-bold">Library access</h3><p className="mt-3 text-sm leading-6 text-white/70">Add official library opening hours, catalogue links, membership instructions and digital-resource URLs here.</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 rounded-lg bg-white px-5 py-3 text-sm font-semibold text-brand-dark">Ask the library <ArrowRight className="h-4 w-4"/></Link></div></div></Section></>
  else if (key==="student-portal") body=<Section><SectionHeading eyebrow="Student Services" title="Everything students need in one place" center/><div className="rounded-2xl border border-border bg-card p-8 text-center"><p className="text-muted-foreground">Open the dedicated student portal.</p><Link href="/student-portal" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-brand px-5 py-3 text-sm font-semibold text-white">Open Student Portal <ArrowRight className="h-4 w-4"/></Link></div></Section>
  else if (key==="faculty") body=<Section><SectionHeading eyebrow="Faculty Directory" title="Meet our academic community" description="Search and filter UI can be connected to the university's official faculty database later."/><div className="mb-7 flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border border-input px-4 py-3"><Search className="h-4 w-4 text-muted-foreground"/><input className="w-full bg-transparent text-sm outline-none" placeholder="Search faculty"/></div><select className="rounded-xl border border-input bg-background px-4 py-3 text-sm"><option>All departments</option>{FACULTIES.map(f=><option key={f.slug}>{f.name}</option>)}</select></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{FACULTY_MEMBERS.map(f=><article key={f.email} className="rounded-2xl border border-border bg-card p-6"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-brand/10 text-brand"><Users className="h-6 w-6"/></div><h3 className="mt-5 font-serif text-xl font-bold">{f.name}</h3><p className="mt-1 text-sm font-medium text-brand">{f.designation}</p><p className="mt-2 text-xs text-muted-foreground">{f.department}</p><a href={`mailto:${f.email}`} className="mt-4 inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-brand"><Mail className="h-3.5 w-3.5"/>{f.email}</a></article>)}</div></Section>
  else if (["login","dashboard","result","pay-fees","hod-login","track-status"].includes(key)) body=<Section><SectionHeading eyebrow="University Service" title={cfg.title} description={cfg.subtitle} center/><div className="mx-auto max-w-2xl rounded-3xl border border-border bg-card p-6 shadow-sm sm:p-8"><div className="space-y-5"><label className="block text-sm font-semibold">Reference / User ID<input className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-brand/20" placeholder="Enter your ID or reference" /></label><label className="block text-sm font-semibold">Password / PIN<input type="password" className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-brand/20" placeholder="Enter password or PIN" /></label><Link href="/contact" className="inline-flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-semibold text-white hover:bg-brand-dark">Continue <ArrowRight className="h-4 w-4"/></Link></div><p className="mt-5 text-xs leading-5 text-muted-foreground">Connect this form to the university authentication or payment backend when those services are available.</p></div></Section>
  else if (["privacy","terms","accessibility"].includes(key)) body=<Section><SectionHeading eyebrow="Website Policy" title={cfg.title} description={cfg.subtitle}/><div className="max-w-none rounded-2xl border border-border bg-card p-6 text-sm leading-7 text-muted-foreground sm:p-8"><p>We are committed to maintaining a clear, respectful and accessible online experience. This page is the official placeholder for the university&apos;s approved {cfg.title.toLowerCase()} content.</p><h2 className="mt-8 font-serif text-2xl font-bold text-foreground">Scope</h2><p className="mt-3">The final policy should be updated with the university&apos;s approved legal wording, responsible office, effective date and contact information before publication.</p><h2 className="mt-8 font-serif text-2xl font-bold text-foreground">Contact</h2><p className="mt-3">For questions about this policy, please use the <Link href="/contact" className="font-semibold text-brand hover:underline">Contact page</Link>.</p></div></Section>
  else if (key==="sitemap") body=<Section><SectionHeading eyebrow="Website Directory" title="Explore the university website" description="Quick links to the main academic, administrative, student and information pages."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{SITEMAP_GROUPS.map(group=><div key={group.title} className="rounded-2xl border border-border bg-card p-6"><h3 className="font-serif text-xl font-bold">{group.title}</h3><div className="mt-4 space-y-2">{group.links.map(([label,href])=><Link key={href} href={href} className="flex items-center justify-between rounded-lg bg-secondary px-3 py-2.5 text-sm font-medium hover:text-brand">{label}<ArrowRight className="h-4 w-4"/></Link>)}</div></div>)}</div></Section>
  else if (key==="campus-life" || key.startsWith("campus-life/")) body=<><Section><SectionHeading eyebrow="Life Beyond Classrooms" title="A campus built for learning, connection and growth"/><Cards items={CAMPUS_LIFE_CARDS.map(c=>({...c,icon:c.icon?ICON_MAP[c.icon]:undefined}))}/></Section></>
  else body=<Section><SectionHeading title={cfg.title} description={cfg.subtitle}/><div className="rounded-2xl border border-border bg-card p-8"><p className="leading-7 text-muted-foreground">This page has been structured for KACST and is ready for official content. Replace the editable placeholder text, dates, names, documents and links with verified university information.</p></div></Section>

  return <Shell cfg={cfg}>{body}</Shell>
}
